on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm i -g npm@8

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm ci

      - run: npm run check

      - run: npm run build -w server
